import Head from "next/head";
import React, { FC } from "react";
import Navbar from "../Navbar";
import styles from "../../styles/Home.module.css";
type Props = {
  children: JSX.Element | JSX.Element[];
};
const MainLayout: FC<Props> = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        {children}
      </main>
    </div>
  );
};

export default MainLayout;
